"""
Pydantic models for ai-service module `crowd`.

AUTOGENERATED by packages/shared-types/scripts/emit-pydantic.mjs —
DO NOT EDIT. Regenerate with `pnpm --filter=@app/shared-types pydantic:emit`.

Drift-gated by `pnpm shared-types:check` (CI `arch` job).
"""


from __future__ import annotations
from datetime import datetime
from enum import Enum
from pydantic import BaseModel, ConfigDict, Field


class CrowdPredictResponseFeatures(BaseModel):
    model_config = ConfigDict(extra='forbid')

    dayOfWeek: float
    hourOfDay: float
    isHoliday: bool


class CrowdDensity(str, Enum):
    empty = "empty"
    light = "light"
    busy = "busy"
    packed = "packed"


class CrowdPredictFeatures(BaseModel):
    model_config = ConfigDict(extra='forbid')

    dayOfWeek: float
    hourOfDay: float
    isHoliday: bool


class CrowdPredictRequest(BaseModel):
    model_config = ConfigDict(extra='forbid')

    placeId: str
    timestamp: datetime


class CrowdPredictResponse(BaseModel):
    model_config = ConfigDict(extra='forbid')

    density: CrowdDensity
    densityScore: float = Field(..., ge=0, le=1)
    confidence: float = Field(..., ge=0, le=1)
    features: CrowdPredictResponseFeatures
