"""
Pydantic models for ai-service module `embeddings`.

AUTOGENERATED by packages/shared-types/scripts/emit-pydantic.mjs —
DO NOT EDIT. Regenerate with `pnpm --filter=@app/shared-types pydantic:emit`.

Drift-gated by `pnpm shared-types:check` (CI `arch` job).
"""


from __future__ import annotations
from typing import Literal
from enum import Enum
from pydantic import BaseModel, ConfigDict, Field


class EmbeddingsPurpose(str, Enum):
    place = "place"
    review = "review"
    query = "query"


class EmbeddingsRequest(BaseModel):
    model_config = ConfigDict(extra='forbid')

    inputs: list[str] = Field(..., min_length=1, max_length=64)
    purpose: EmbeddingsPurpose


class EmbeddingsResponse(BaseModel):
    model_config = ConfigDict(extra='forbid')

    model: str
    dimensions: Literal[1024]
    embeddings: list[list[float]]
