"""
Pydantic models for ai-service module `fake-review`.

AUTOGENERATED by packages/shared-types/scripts/emit-pydantic.mjs —
DO NOT EDIT. Regenerate with `pnpm --filter=@app/shared-types pydantic:emit`.

Drift-gated by `pnpm shared-types:check` (CI `arch` job).
"""


from __future__ import annotations
from datetime import datetime
from enum import Enum
from pydantic import BaseModel, ConfigDict, Field


class FakeReviewScoreRequestReviews(BaseModel):
    model_config = ConfigDict(extra='forbid')

    id: str
    authorId: str
    body: str = Field(..., min_length=1, max_length=8000)
    postedAt: datetime


class FakeReviewScoreResponseResults(BaseModel):
    model_config = ConfigDict(extra='forbid')

    id: str
    score: float = Field(..., ge=0, le=1)
    label: FakeReviewLabel
    reasons: list[str] = Field(..., max_length=4)


class FakeReviewLabel(str, Enum):
    real = "real"
    suspicious = "suspicious"
    fake = "fake"


class FakeReviewScoreInputReview(BaseModel):
    model_config = ConfigDict(extra='forbid')

    id: str
    authorId: str
    body: str = Field(..., min_length=1, max_length=8000)
    postedAt: datetime


class FakeReviewScoreRequest(BaseModel):
    model_config = ConfigDict(extra='forbid')

    reviews: list[FakeReviewScoreRequestReviews] = Field(..., min_length=1, max_length=100)


class FakeReviewScoreResponse(BaseModel):
    model_config = ConfigDict(extra='forbid')

    results: list[FakeReviewScoreResponseResults]


class FakeReviewScoreResult(BaseModel):
    model_config = ConfigDict(extra='forbid')

    id: str
    score: float = Field(..., ge=0, le=1)
    label: FakeReviewLabel
    reasons: list[str] = Field(..., max_length=4)
