"""
Pydantic models for ai-service module `health`.

AUTOGENERATED by packages/shared-types/scripts/emit-pydantic.mjs —
DO NOT EDIT. Regenerate with `pnpm --filter=@app/shared-types pydantic:emit`.

Drift-gated by `pnpm shared-types:check` (CI `arch` job).
"""


from __future__ import annotations
from typing import Literal
from pydantic import BaseModel, ConfigDict, Field


class AiServiceHealthResponseRay(BaseModel):
    model_config = ConfigDict(extra='forbid')

    replicas: int = Field(..., ge=0)
    healthy: int = Field(..., ge=0)


class AiServiceHealthResponse(BaseModel):
    model_config = ConfigDict(extra='forbid')

    status: Literal["ok"]
    ray: AiServiceHealthResponseRay
