"""
Pydantic models for ai-service module `stt`.

AUTOGENERATED by packages/shared-types/scripts/emit-pydantic.mjs —
DO NOT EDIT. Regenerate with `pnpm --filter=@app/shared-types pydantic:emit`.

Drift-gated by `pnpm shared-types:check` (CI `arch` job).
"""


from __future__ import annotations
from typing import Union
from pydantic import BaseModel, ConfigDict, Field


class STTChunk(BaseModel):
    model_config = ConfigDict(extra='forbid')

    audio: Union[bytes, str]
    sampleRateHz: int = Field(..., gt=0)
    final: bool


class STTPartial(BaseModel):
    model_config = ConfigDict(extra='forbid')

    text: str
    isFinal: bool
    confidence: float = Field(..., ge=0, le=1)
