"""
Pydantic models for ai-service module `translate`.

AUTOGENERATED by packages/shared-types/scripts/emit-pydantic.mjs —
DO NOT EDIT. Regenerate with `pnpm --filter=@app/shared-types pydantic:emit`.

Drift-gated by `pnpm shared-types:check` (CI `arch` job).
"""


from __future__ import annotations
from typing import Optional
from enum import Enum
from pydantic import BaseModel, ConfigDict, Field


class TranslateDomain(str, Enum):
    general = "general"
    food = "food"
    navigation = "navigation"
    safety = "safety"


class TranslateRequest(BaseModel):
    model_config = ConfigDict(extra='forbid')

    sourceLang: str = Field(..., min_length=2, max_length=2)
    targetLang: str = Field(..., min_length=2, max_length=2)
    text: str = Field(..., min_length=1, max_length=4000)
    domain: Optional[TranslateDomain] = None


class TranslateResponse(BaseModel):
    model_config = ConfigDict(extra='forbid')

    text: str
    modelVersion: str
    cacheHit: bool
    latencyMs: int = Field(..., ge=0)
