/**
 * V.UX.5 PDF document. Pure-data layout — title block on page 1,
 * day-by-day itinerary, emergency contacts footer. No images,
 * keeps the bundle + render time low.
 *
 * Lives in its own file so the heavy `@react-pdf/renderer` import
 * stays out of the main trip-page chunk (`export-pdf-button.tsx`
 * lazy-imports this on click).
 *
 * Installed by prompt [V.UX.5].
 */
'use client';

import type { ReactElement } from 'react';
import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer';
import type { ItineraryDayDto, ItineraryItemDto, TripDto } from '@app/sdk';

interface TripPdfDocumentProps {
  readonly trip: TripDto;
  readonly days: readonly ItineraryDayDto[];
}

const styles = StyleSheet.create({
  page: {
    padding: 36,
    fontSize: 11,
    fontFamily: 'Helvetica',
    color: '#222',
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  meta: {
    fontSize: 10,
    color: '#666',
    marginBottom: 16,
  },
  dayHeader: {
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 12,
    marginBottom: 4,
    color: '#1a1a1a',
  },
  daySummary: {
    fontSize: 10,
    color: '#555',
    marginBottom: 6,
  },
  itemRow: {
    flexDirection: 'row',
    marginBottom: 3,
  },
  itemBullet: {
    width: 14,
    fontSize: 10,
  },
  itemBody: {
    flex: 1,
    fontSize: 10,
  },
  emptyDay: {
    fontSize: 10,
    color: '#999',
    fontStyle: 'italic',
  },
  emergencyHeader: {
    marginTop: 24,
    fontSize: 12,
    fontWeight: 'bold',
    color: '#1a1a1a',
  },
  emergencyBody: {
    fontSize: 10,
    color: '#555',
    marginTop: 4,
    lineHeight: 1.4,
  },
  footer: {
    position: 'absolute',
    bottom: 18,
    left: 36,
    right: 36,
    fontSize: 8,
    color: '#999',
    textAlign: 'center',
  },
});

export function TripPdfDocument({ trip, days }: TripPdfDocumentProps): ReactElement {
  const startsOn = trip.startsOn ? new Date(trip.startsOn as unknown as string) : null;
  const endsOn = trip.endsOn ? new Date(trip.endsOn as unknown as string) : null;
  const dateRange =
    startsOn && endsOn
      ? `${startsOn.toLocaleDateString()} → ${endsOn.toLocaleDateString()}`
      : 'No dates set';
  return (
    <Document title={trip.title} author="Travel Super App">
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{trip.title}</Text>
        <Text style={styles.meta}>
          {dateRange} · {trip.radiusKm}km radius · status: {trip.status}
        </Text>

        {days.length === 0 ? (
          <Text style={styles.emptyDay}>
            No itinerary generated yet. Generate one in the app and re-export.
          </Text>
        ) : (
          days.map((d, i) => <DayBlock key={d.id} day={d} index={i} />)
        )}

        <Text style={styles.emergencyHeader}>Emergency contacts</Text>
        <Text style={styles.emergencyBody}>
          Local emergency: dial the country&apos;s 3-digit emergency line on arrival.{'\n'}
          App support: support@travel.example{'\n'}
          Carry a printed copy of your passport + insurance documents.
        </Text>

        <Text style={styles.footer} fixed>
          Generated by Travel Super App · {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
}

function DayBlock({ day, index }: { day: ItineraryDayDto; index: number }) {
  const date = new Date(day.date as unknown as string);
  const summary = day.summary as unknown as string | null;
  return (
    <View wrap={false}>
      <Text style={styles.dayHeader}>
        Day {index + 1} — {date.toLocaleDateString()}
      </Text>
      {summary ? <Text style={styles.daySummary}>{summary}</Text> : null}
      {day.items.length === 0 ? (
        <Text style={styles.emptyDay}>(no items)</Text>
      ) : (
        day.items.map((it) => <Item key={it.id} item={it} />)
      )}
    </View>
  );
}

function Item({ item }: { item: ItineraryItemDto }) {
  const notes = (item.notes as unknown as string | null) ?? '(no notes)';
  const placeId = item.placeId as unknown as string | null;
  return (
    <View style={styles.itemRow}>
      <Text style={styles.itemBullet}>•</Text>
      <Text style={styles.itemBody}>
        {notes}
        {placeId ? `  [${placeId.slice(0, 8)}…]` : ''}
      </Text>
    </View>
  );
}
