#!/usr/bin/env bash
# Dev bootstrap — one-command local up for TravelSuperApp.
#
#   bash scripts/dev-bootstrap.sh            # bootstrap only
#   bash scripts/dev-bootstrap.sh --verify   # bootstrap + boot api + poll /health/ready
#
# Brings up Postgres + Redis + Meilisearch + MinIO via docker compose,
# generates apps/api/.env.local + apps/web/.env.local on first run,
# applies Prisma migrations, and seeds demo data. Idempotent — re-running
# is safe; existing env files are not overwritten.
#
# With --verify (used by CI bootstrap-smoke and by humans who want
# end-to-end proof): starts apps/api in the background, polls
# http://127.0.0.1:3000/health/ready for up to 90s, then stops it.
# Exits non-zero with a diagnostic if the api fails to become ready.
#
# After this completes (no --verify), in two separate terminals:
#   pnpm --filter=api dev    # NestJS on :3000
#   pnpm --filter=web dev    # Next.js on :3001
#
# Installed by prompt [IV.18.19.49.x bootstrap]. Verify flag added by [P2].
set -euo pipefail

VERIFY=0
for arg in "$@"; do
  case "$arg" in
    --verify) VERIFY=1 ;;
    -h|--help)
      sed -n '2,22p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) printf "unknown flag: %s\n" "$arg" >&2; exit 2 ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

step() { printf "\n\033[1;36m▸ %s\033[0m\n" "$*"; }
ok()   { printf "  \033[1;32m✓\033[0m %s\n" "$*"; }
warn() { printf "  \033[1;33m!\033[0m %s\n" "$*"; }

require() {
  if ! command -v "$1" >/dev/null 2>&1; then
    printf "\033[1;31m✗ missing: %s\033[0m  (%s)\n" "$1" "${2:-please install it}"
    exit 1
  fi
}

# ── 1. preflight ────────────────────────────────────────────────────────
step "preflight"
require docker "https://docs.docker.com/get-docker/"
require pnpm   "corepack enable && corepack prepare pnpm@latest --activate"
require node   "https://nodejs.org/  (>= 22)"
ok "docker, pnpm, node found"

# ── 2. env files (generate only if absent — never overwrite secrets) ────
step "env files"
gen_secret() { node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"; }

API_ENV="apps/api/.env.local"
if [ -f "$API_ENV" ]; then
  ok "$API_ENV already exists — leaving it alone"
else
  warn "$API_ENV missing — generating with random dev secrets"
  cat > "$API_ENV" <<EOF
# Auto-generated by scripts/dev-bootstrap.sh. Gitignored — never commit.
NODE_ENV=development
PORT=3000
LOG_LEVEL=info

DATABASE_URL=postgresql://travel:travel_dev@localhost:5432/travel_dev
DATABASE_POOL_MIN=2
DATABASE_POOL_MAX=10

REDIS_URL=redis://:redis_dev@localhost:6379

JWT_ACCESS_SECRET=$(gen_secret)
JWT_REFRESH_SECRET=$(gen_secret)
JWT_ACCESS_EXPIRY=15m
JWT_REFRESH_EXPIRY=30d

AI_SERVICE_URL=http://localhost:8001

S3_ENDPOINT=http://localhost:9000
S3_BUCKET=travel-dev
S3_ACCESS_KEY=minio
S3_SECRET_KEY=minio_dev_password
S3_REGION=us-east-1

MEILI_HOST=http://localhost:7700
MEILI_MASTER_KEY=meili_dev_key_change_me_minimum_16_chars

FEATURE_3D_ENABLED=false
FEATURE_SATELLITE_CROWD=false

RATE_LIMIT_PEPPER=$(gen_secret)
EMAIL_PEPPER=$(gen_secret)
BACKUP_CODE_PEPPER=$(gen_secret)

CORS_ORIGINS=http://localhost:3001
EOF
  ok "wrote $API_ENV with fresh dev peppers"
fi

WEB_ENV="apps/web/.env.local"
if [ -f "$WEB_ENV" ]; then
  ok "$WEB_ENV already exists — leaving it alone"
else
  warn "$WEB_ENV missing — generating"
  cat > "$WEB_ENV" <<'EOF'
# Auto-generated by scripts/dev-bootstrap.sh. Gitignored — never commit.
NEXT_PUBLIC_API_URL=http://localhost:3000
# NEXT_PUBLIC_GOOGLE_CLIENT_ID=    # uncomment + set to enable real Google Sign-In
EOF
  ok "wrote $WEB_ENV"
fi

# ── 3. docker stack ─────────────────────────────────────────────────────
step "docker stack"
docker compose -f infra/docker-compose.yml up -d
ok "compose stack up — waiting for healthchecks"
# Wait for postgres + redis to settle. Compose healthchecks already gate
# this, but `up -d` returns before they're green; loop until pg_isready.
for i in $(seq 1 30); do
  if docker compose -f infra/docker-compose.yml exec -T postgres pg_isready -U travel -d travel_dev >/dev/null 2>&1; then
    ok "postgres healthy"
    break
  fi
  sleep 1
  if [ "$i" = 30 ]; then
    printf "\033[1;31m✗ postgres not ready after 30s\033[0m\n"
    exit 1
  fi
done

# ── 4. install + prisma generate (no-op if up to date) ──────────────────
step "node deps"
pnpm install --prefer-offline >/dev/null
ok "pnpm install complete"

step "prisma client"
pnpm --filter=api db:generate >/dev/null
ok "prisma client generated"

# ── 5. migrations + seed ────────────────────────────────────────────────
step "prisma migrate"
pnpm --filter=api db:migrate:deploy
ok "migrations applied"

step "seed demo data"
if pnpm --filter=api db:seed:demo; then
  ok "demo data seeded — check /featured + create a user via /register"
else
  warn "seed step failed — repo can still be used, but /featured will be empty until you run pnpm --filter=api db:seed:demo manually"
fi

# ── 6. summary ──────────────────────────────────────────────────────────
printf "\n\033[1;32m── ready ──\033[0m\n"
printf "  api:  pnpm --filter=api dev   (http://localhost:3000)\n"
printf "  web:  pnpm --filter=web dev   (http://localhost:3001)\n"
printf "\n  postgres :5432  redis :6379  meilisearch :7700  minio :9000 (console :9001)\n"
printf "  stop stack:  docker compose -f infra/docker-compose.yml down\n"

# ── 7. optional verify (--verify) ───────────────────────────────────────
# Boots apps/api in the background, polls /health/ready until 200 OR 90s,
# then kills the background api. This is the CI smoke-test path and is the
# only way to be SURE that bootstrap actually produces a running system.
if [ "$VERIFY" = "1" ]; then
  step "verify api boots + /health/ready=200"

  API_LOG="$(mktemp -t travel-api-verify.XXXXXX.log)"
  ( cd "$REPO_ROOT" && pnpm --filter=api start:dev >"$API_LOG" 2>&1 ) &
  API_PID=$!
  trap 'kill "$API_PID" 2>/dev/null || true' EXIT

  ok "api booting in background (pid $API_PID, log $API_LOG)"

  READY=0
  # Poll for up to 90s. Use 127.0.0.1 not localhost — Windows resolves
  # localhost to IPv6 and Docker only listens on IPv4 (memory:
  # localhost-ipv6-postgres).
  for i in $(seq 1 90); do
    if curl -fsS -m 2 http://127.0.0.1:3000/health/ready >/dev/null 2>&1; then
      READY=1
      ok "/health/ready=200 after ${i}s"
      break
    fi
    if ! kill -0 "$API_PID" 2>/dev/null; then
      printf "\033[1;31m✗ api process exited before becoming ready\033[0m\n" >&2
      tail -n 100 "$API_LOG" >&2 || true
      exit 1
    fi
    sleep 1
  done

  if [ "$READY" != "1" ]; then
    printf "\033[1;31m✗ /health/ready never returned 200 after 90s\033[0m\n" >&2
    printf "  last 100 lines of api log (%s):\n" "$API_LOG" >&2
    tail -n 100 "$API_LOG" >&2 || true
    exit 1
  fi

  # Light second probe — exercise /health/live + /metrics so we know
  # observability + the liveness probe are wired, not just the readiness gate.
  curl -fsS -m 2 http://127.0.0.1:3000/health/live >/dev/null 2>&1 || {
    printf "\033[1;31m✗ /health/live did not respond\033[0m\n" >&2
    exit 1
  }
  ok "/health/live=200"

  curl -fsS -m 2 http://127.0.0.1:3000/metrics 2>/dev/null | head -n 1 | grep -q '^# HELP\|^# TYPE\|^[a-z]' && ok "/metrics emits prometheus exposition" || warn "/metrics empty — observability may be gated off"

  kill "$API_PID" 2>/dev/null || true
  wait "$API_PID" 2>/dev/null || true
  ok "verify complete — system bootstraps end-to-end"
fi
